### ISSUE TITLE
Listview does not exist on type 'GameObjectFactory;

### ISSUE THREAD

**Issue by louieseno** [iamchristopher/phaser-plugin-list-view#6]
<img width="1440" alt="Screen Shot 2019-11-02 at 10 57 33 AM" src="https://user-images.githubusercontent.com/33439106/68065150-b3b1b880-fd5f-11e9-814f-75a360dd2118.png">

**Comment by jorbascrumps** [comment]
Hi @louieseno! Thanks for submitting this issue!

I don't normally work with TypeScript so I didn't think to include types. I'll take a look at this shortly.
